[build]
  base = "ui/trading-bot-ui"  # Set to frontend directory
  publish = "ui/trading-bot-ui/build"  # Directory to deploy after build
  command = "ESLINT_NO_DEV_ERRORS=true npm install && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
